version: "3.3"
services:
  web:
    container_name: business_tracker_web
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - .:/src/app
  # adminer:
  #   image: adminer
  #   container_name: business_tracker_adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - app-tier